steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - --platform=linux/amd64
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/projectkit/app:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/projectkit/app:latest
      - .

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - --all-tags
      - us-central1-docker.pkg.dev/$PROJECT_ID/projectkit/app

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - projectkit
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/projectkit/app:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --quiet

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/projectkit/app:$COMMIT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/projectkit/app:latest

options:
  logging: CLOUD_LOGGING_ONLY
